import type { Question, SymptomCategory } from './types'

/**
 * Standardized "Not sure" option required across all clinical questions
 */
const NOT_SURE_OPTION = {
  id: 'not_sure',
  label: 'Not sure',
  value: 'not_sure',
}

/**
 * Approved Question Library for HEALNEST
 *
 * Deterministic questionnaire specifications for:
 * 1. Burn
 * 2. Stomach Pain
 * 3. Headache
 */
export const QUESTION_LIBRARY: Record<SymptomCategory, Question[]> = {
  burn: [
    {
      id: 'burn_cause',
      category: 'burn',
      text: 'What caused the burn?',
      subtext: 'Different sources have distinct clinical risks and tissue depth profiles.',
      whyText:
        'The source of a burn determines how deep the heat penetrated and whether specialized neutralization (for chemicals) or cardiac monitoring (for electricity) is needed.',
      isCriticalForOutcome: true,
      options: [
        { id: 'hot_liquid', label: 'Hot liquid (scald)', value: 'hot_liquid' },
        { id: 'hot_object', label: 'Hot object (contact)', value: 'hot_object' },
        { id: 'fire_flame', label: 'Fire or open flame', value: 'fire_flame' },
        { id: 'chemical', label: 'Chemical substance', value: 'chemical', redFlag: true },
        { id: 'electricity', label: 'Electricity or electrical outlet', value: 'electricity', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'burn_breathing',
      category: 'burn',
      text: 'Is there any difficulty breathing, smoke inhalation, or coughing up soot?',
      subtext: 'Airway burns and smoke inhalation can rapidly worsen.',
      whyText:
        'Smoke inhalation or hot air can scorch the airway and cause rapid swelling that obstructs breathing. This is an immediate medical emergency.',
      isRedFlagTrigger: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'burn_location',
      category: 'burn',
      text: 'Is the burn on the face, hands, feet, genitals, or across a major joint?',
      subtext: 'Burns in these delicate anatomical areas require specialist clinical assessment.',
      whyText:
        'Burns on hands, feet, face, genitals, or major joints can lead to severe scarring, infection, or loss of mobility and require specialist burn clinic care.',
      isRedFlagTrigger: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'burn_size',
      category: 'burn',
      text: 'What is the approximate size of the burned area?',
      subtext: "Compare the area to the size of the affected person's palm (including fingers).",
      whyText:
        'The percentage of body surface area burned directly affects fluid loss and determines whether clinical wound therapy or fluid replacement is necessary.',
      isCriticalForOutcome: true,
      options: [
        { id: 'smaller_than_palm', label: 'Smaller than palm', value: 'smaller_than_palm' },
        { id: 'about_palm_size', label: 'About palm size', value: 'about_palm_size' },
        { id: 'larger_than_palm', label: 'Larger than palm', value: 'larger_than_palm' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'burn_skin',
      category: 'burn',
      text: 'What does the burned skin look like?',
      subtext: 'Assesses the depth of burn from superficial to full-thickness.',
      whyText:
        'Skin appearance reveals whether the burn is superficial (red), partial-thickness (blistering), or full-thickness (leathery/blackened) which destroys deeper tissues.',
      isCriticalForOutcome: true,
      options: [
        { id: 'normal_red', label: 'Red and painful without blisters (like mild sunburn)', value: 'normal_red' },
        { id: 'blistered', label: 'Forming fluid-filled blisters', value: 'blistered' },
        { id: 'peeling_damaged', label: 'Peeling, raw, or weeping skin', value: 'peeling_damaged' },
        { id: 'white_blackened', label: 'White, waxy, leathery, or charred/blackened', value: 'white_blackened', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
  ],

  stomach_pain: [
    {
      id: 'stomach_red_flags',
      category: 'stomach_pain',
      text: 'Is your abdomen rigid or board-like to the touch, or are you vomiting blood / dark material?',
      subtext: 'Identifies acute internal hemorrhage or peritonitis requiring emergency care.',
      whyText:
        'A rigid board-like belly or vomiting blood indicates acute internal bleeding or a perforated abdominal organ requiring immediate emergency evaluation.',
      isRedFlagTrigger: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'stomach_duration',
      category: 'stomach_pain',
      text: 'How long have you had this stomach pain?',
      subtext: 'Helps distinguish acute from persistent or chronic pain.',
      whyText:
        'Acute pain starting abruptly often has different causes (like appendicitis or gallstones) compared to pain lasting several days.',
      isCriticalForOutcome: true,
      options: [
        { id: 'less_6h', label: 'Less than 6 hours', value: 'less_6h' },
        { id: '1_day', label: 'About 1 day', value: '1_day' },
        { id: '2_3_days', label: '2 to 3 days', value: '2_3_days' },
        { id: 'longer_3_days', label: 'Longer than 3 days', value: 'longer_3_days' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'stomach_severity',
      category: 'stomach_pain',
      text: 'How severe is the pain?',
      subtext: 'Rate the intensity of your discomfort.',
      whyText:
        'Pain intensity helps assess how urgently your abdomen needs to be examined by a clinician.',
      isCriticalForOutcome: true,
      options: [
        { id: 'mild', label: 'Mild (noticeable but can carry out normal activities)', value: 'mild' },
        { id: 'moderate', label: 'Moderate (interferes with normal activities)', value: 'moderate' },
        { id: 'severe', label: 'Severe (incapacitating or unable to stand straight)', value: 'severe' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'stomach_location',
      category: 'stomach_pain',
      text: 'Where is the pain located?',
      subtext: 'Anatomical quadrant helps guide clinical urgency.',
      whyText:
        'Different organs lie in different parts of your abdomen (e.g. gallbladder in upper right, appendix in lower right). Knowing the location helps identify the underlying cause.',
      isCriticalForOutcome: false,
      options: [
        { id: 'upper', label: 'Upper abdomen (stomach / under ribs)', value: 'upper' },
        { id: 'lower', label: 'Lower abdomen (pelvic area)', value: 'lower' },
        { id: 'whole', label: 'All over the whole abdomen', value: 'whole' },
        { id: 'localized', label: 'One specific spot on right or left', value: 'localized' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'stomach_associated',
      category: 'stomach_pain',
      text: 'Are you experiencing any of these associated symptoms?',
      subtext: 'Select all that currently apply.',
      whyText:
        'Fever, repeated vomiting, or bleeding signal systemic infection or dehydration risk rather than simple indigestion.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'vomiting', label: 'Frequent vomiting', value: 'vomiting' },
        { id: 'fever', label: 'High fever or chills', value: 'fever' },
        { id: 'blood_in_stool', label: 'Blood in stool or black tarry stools', value: 'blood_in_stool', redFlag: true },
        { id: 'no_fluids', label: 'Inability to keep down fluids for over 12 hours', value: 'no_fluids' },
        { id: 'none', label: 'None of the above', value: 'none' },
        NOT_SURE_OPTION,
      ],
    },
  ],

  headache: [
    {
      id: 'headache_red_flags',
      category: 'headache',
      text: 'Did this headache strike suddenly as the "worst headache of your life", or is it accompanied by confusion, vision loss, or stiff neck with fever?',
      subtext: 'Critical screening for subarachnoid hemorrhage, meningitis, or intracranial events.',
      whyText:
        'Sudden explosive headaches or those with neurological symptoms can indicate bleeding in the brain or severe infection that requires immediate emergency evaluation.',
      isRedFlagTrigger: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'headache_onset',
      category: 'headache',
      text: 'How quickly did the headache start and reach peak intensity?',
      subtext: 'Sudden onset (thunderclap) is clinically distinct from gradual onset.',
      whyText:
        'A headache reaching peak severity in seconds ("thunderclap") is a hallmark warning sign of subarachnoid hemorrhage, whereas gradual headaches are more commonly benign tension or migraine.',
      isCriticalForOutcome: true,
      options: [
        { id: 'sudden', label: 'Sudden "thunderclap" (peaked within seconds or minutes)', value: 'sudden', redFlag: true },
        { id: 'gradual', label: 'Gradual (developed steadily over hours or days)', value: 'gradual' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'headache_severity',
      category: 'headache',
      text: 'How would you describe the severity of this headache?',
      subtext: 'Pain intensity comparison against past experiences.',
      whyText:
        'Tracking pain severity helps distinguish routine manageable headaches from severe episodes that require clinical intervention.',
      isCriticalForOutcome: true,
      options: [
        { id: 'mild', label: 'Mild (dull ache, manageable)', value: 'mild' },
        { id: 'moderate', label: 'Moderate (throbbing, limits daily tasks)', value: 'moderate' },
        { id: 'severe', label: 'Severe (unbearable, need to lie in the dark)', value: 'severe' },
        { id: 'worst_ever', label: 'Worst headache I have ever experienced', value: 'worst_ever', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'headache_associated',
      category: 'headache',
      text: 'Do you have any of these associated symptoms?',
      subtext: 'Select all neurological or systemic symptoms present.',
      whyText:
        'Neck stiffness with fever can indicate bacterial meningitis, while vision changes or weakness can signal elevated intracranial pressure or a vascular event.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'stiff_neck_fever', label: 'Stiff neck accompanied by fever', value: 'stiff_neck_fever', redFlag: true },
        { id: 'vision_loss', label: 'Vision loss, double vision, or visual aura', value: 'vision_loss', redFlag: true },
        { id: 'confusion_weakness', label: 'Confusion, slurred speech, or weakness in face/arm/leg', value: 'confusion_weakness', redFlag: true },
        { id: 'light_sound_sensitivity', label: 'Sensitivity to light or sound, or nausea', value: 'light_sound_sensitivity' },
        { id: 'none', label: 'None of the above', value: 'none' },
        NOT_SURE_OPTION,
      ],
    },
  ],

  fever: [
    {
      id: 'fever_temperature',
      category: 'fever',
      text: 'What is the current body temperature?',
      subtext: 'High fevers (above 103°F / 39.4°C) require different management than low-grade fevers.',
      whyText: 'Temperature range helps distinguish a mild physiological response from a severe systemic infection.',
      isCriticalForOutcome: true,
      options: [
        { id: 'low_grade', label: 'Low-grade (99.5°F - 100.3°F / 37.5°C - 37.9°C)', value: 'low_grade' },
        { id: 'moderate', label: 'Moderate (100.4°F - 102.9°F / 38.0°C - 39.3°C)', value: 'moderate' },
        { id: 'high', label: 'High (103°F / 39.4°C or above)', value: 'high', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'fever_duration',
      category: 'fever',
      text: 'How long has the fever been present?',
      subtext: 'Prolonged fevers need clinical investigation.',
      whyText: 'Fever lasting more than 3-5 days may indicate a persistent infection needing antibiotics or further workup.',
      isCriticalForOutcome: true,
      options: [
        { id: 'less_3_days', label: 'Less than 3 days', value: 'less_3_days' },
        { id: '3_to_5_days', label: '3 to 5 days', value: '3_to_5_days' },
        { id: 'more_5_days', label: 'More than 5 days', value: 'more_5_days' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'fever_associated',
      category: 'fever',
      text: 'Are there any associated symptoms?',
      subtext: 'Select all that apply.',
      whyText: 'Neck stiffness, rash, or confusion can indicate meningitis or sepsis, requiring emergency care.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'stiff_neck', label: 'Severe stiff neck', value: 'stiff_neck', redFlag: true },
        { id: 'rash', label: 'New unexplained rash', value: 'rash' },
        { id: 'confusion', label: 'Confusion or difficulty waking up', value: 'confusion', redFlag: true },
        { id: 'breathing_diff', label: 'Difficulty breathing', value: 'breathing_diff', redFlag: true },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
    {
      id: 'fever_status',
      category: 'fever',
      text: 'Is the patient immunocompromised, undergoing chemotherapy, or very young/old?',
      subtext: 'Vulnerable populations have a lower threshold for sepsis.',
      whyText: 'Individuals with weakened immune systems can deteriorate rapidly from infections that would otherwise be mild.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes' },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  cough: [
    {
      id: 'cough_duration',
      category: 'cough',
      text: 'How long have you had this cough?',
      subtext: 'Acute vs chronic cough helps narrow down the cause.',
      whyText: 'A cough lasting more than 3-8 weeks is considered chronic and requires investigation for asthma, GERD, or other conditions.',
      isCriticalForOutcome: true,
      options: [
        { id: 'less_3_weeks', label: 'Less than 3 weeks', value: 'less_3_weeks' },
        { id: '3_to_8_weeks', label: '3 to 8 weeks', value: '3_to_8_weeks' },
        { id: 'more_8_weeks', label: 'More than 8 weeks (chronic)', value: 'more_8_weeks' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'cough_sputum',
      category: 'cough',
      text: 'Are you coughing up any blood or significantly discolored mucus?',
      subtext: 'Blood in sputum is a critical finding.',
      whyText: 'Coughing up blood (hemoptysis) can indicate severe infection, pulmonary embolism, or malignancy, requiring urgent evaluation.',
      isCriticalForOutcome: true,
      options: [
        { id: 'blood', label: 'Yes, coughing up blood', value: 'blood', redFlag: true },
        { id: 'discolored', label: 'Yes, thick yellow/green mucus', value: 'discolored' },
        { id: 'clear', label: 'No, clear/white mucus or dry cough', value: 'clear' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'cough_associated',
      category: 'cough',
      text: 'Are you experiencing breathing difficulties or chest pain?',
      subtext: 'Assess for respiratory distress or cardiac involvement.',
      whyText: 'Severe shortness of breath or chest pain can be signs of pneumonia, asthma exacerbation, or a pulmonary embolism.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'shortness_breath', label: 'Severe shortness of breath at rest', value: 'shortness_breath', redFlag: true },
        { id: 'chest_pain', label: 'Chest pain', value: 'chest_pain' },
        { id: 'fever', label: 'High fever', value: 'fever' },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
  ],
  rash: [
    {
      id: 'rash_onset',
      category: 'rash',
      text: 'How quickly did the rash appear?',
      subtext: 'Sudden spreading rashes can indicate systemic reactions.',
      whyText: 'A rapidly spreading rash, especially over minutes to hours, can be a sign of anaphylaxis or severe drug reaction.',
      isCriticalForOutcome: true,
      options: [
        { id: 'sudden', label: 'Suddenly (within minutes to hours) and spreading fast', value: 'sudden', redFlag: true },
        { id: 'gradual', label: 'Gradually over days', value: 'gradual' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'rash_appearance',
      category: 'rash',
      text: 'What does the rash look like?',
      subtext: 'Visual characteristics of the rash.',
      whyText: 'Blisters can indicate shingles or severe reactions, while non-blanching spots (petechiae) can indicate a bleeding disorder or meningitis.',
      isCriticalForOutcome: true,
      options: [
        { id: 'red_bumpy', label: 'Red, itchy, and bumpy (hives/welts)', value: 'red_bumpy' },
        { id: 'blistering', label: 'Blistering, peeling, or painful', value: 'blistering' },
        { id: 'purple_spots', label: 'Dark purple/red spots that do not fade when pressed', value: 'purple_spots', redFlag: true },
        { id: 'dry_scaly', label: 'Dry, scaly, or patchy', value: 'dry_scaly' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'rash_associated',
      category: 'rash',
      text: 'Are you experiencing any swelling or breathing difficulty?',
      subtext: 'Check for signs of anaphylaxis.',
      whyText: 'Facial swelling and breathing difficulties accompanying a rash are classic signs of a life-threatening allergic reaction.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, swelling of face/lips/tongue or breathing trouble', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  chest_pain: [
    {
      id: 'chest_pain_character',
      category: 'chest_pain',
      text: 'How would you describe the pain?',
      subtext: 'Pain quality helps differentiate cardiac from non-cardiac causes.',
      whyText: 'Crushing, heavy, or squeezing pain is classically associated with myocardial infarction (heart attack).',
      isCriticalForOutcome: true,
      options: [
        { id: 'crushing', label: 'Crushing, heavy pressure, or squeezing', value: 'crushing', redFlag: true },
        { id: 'sharp', label: 'Sharp or stabbing (worse with breathing/coughing)', value: 'sharp' },
        { id: 'burning', label: 'Burning sensation', value: 'burning' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'chest_pain_radiation',
      category: 'chest_pain',
      text: 'Does the pain spread anywhere else?',
      subtext: 'Radiation patterns are key clinical indicators.',
      whyText: 'Pain radiating to the left arm, jaw, neck, or back is highly suspicious for acute coronary syndrome or aortic dissection.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'arm_jaw', label: 'Yes, to the arm, jaw, neck, or back', value: 'arm_jaw', redFlag: true },
        { id: 'no', label: 'No, it stays in the chest', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'chest_pain_associated',
      category: 'chest_pain',
      text: 'Do you have any of these associated symptoms?',
      subtext: 'Select all that apply.',
      whyText: 'Sweating, shortness of breath, and nausea accompanying chest pain strongly suggest a cardiac event.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'sob', label: 'Shortness of breath', value: 'sob', redFlag: true },
        { id: 'sweating', label: 'Cold sweats or nausea', value: 'sweating', redFlag: true },
        { id: 'dizziness', label: 'Lightheadedness or fainting', value: 'dizziness', redFlag: true },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
  ],
  back_pain: [
    {
      id: 'back_pain_cause',
      category: 'back_pain',
      text: 'Did the pain start after an injury or trauma?',
      subtext: 'Trauma increases risk of fractures.',
      whyText: 'A fall from height or high-impact trauma can cause spinal fractures or spinal cord injury.',
      isCriticalForOutcome: true,
      options: [
        { id: 'major_trauma', label: 'Yes, severe trauma (e.g. car crash, major fall)', value: 'major_trauma', redFlag: true },
        { id: 'minor_strain', label: 'Yes, minor injury or lifting heavy object', value: 'minor_strain' },
        { id: 'no_trauma', label: 'No obvious injury', value: 'no_trauma' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'back_pain_neurological',
      category: 'back_pain',
      text: 'Are you experiencing numbness, weakness, or loss of bowel/bladder control?',
      subtext: 'Assess for spinal cord or nerve root compression.',
      whyText: 'Cauda equina syndrome is a surgical emergency characterized by loss of bowel/bladder control and numbness in the saddle area.',
      isCriticalForOutcome: true,
      options: [
        { id: 'bowel_bladder', label: 'Yes, loss of bowel or bladder control', value: 'bowel_bladder', redFlag: true },
        { id: 'numbness_weakness', label: 'Yes, severe numbness or weakness in legs', value: 'numbness_weakness', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'back_pain_associated',
      category: 'back_pain',
      text: 'Do you have a fever or unexplained weight loss?',
      subtext: 'Assess for infection or malignancy.',
      whyText: 'Fever with back pain can indicate a spinal infection, while unexplained weight loss could suggest a malignancy.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, fever or weight loss', value: 'yes' },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  dizziness: [
    {
      id: 'dizziness_type',
      category: 'dizziness',
      text: 'How does the dizziness feel?',
      subtext: 'Vertigo vs presyncope vs disequilibrium.',
      whyText: 'A spinning sensation (vertigo) points to inner ear issues, while feeling faint (presyncope) points to cardiovascular issues.',
      isCriticalForOutcome: true,
      options: [
        { id: 'spinning', label: 'Room is spinning (Vertigo)', value: 'spinning' },
        { id: 'faint', label: 'Feeling like I might pass out', value: 'faint' },
        { id: 'unsteady', label: 'Unsteady, off-balance', value: 'unsteady' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'dizziness_stroke_signs',
      category: 'dizziness',
      text: 'Are you experiencing slurred speech, facial droop, or arm weakness?',
      subtext: 'Check for FAST signs of a stroke.',
      whyText: 'Dizziness accompanied by focal neurological deficits (FAST signs) strongly suggests an acute stroke.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'dizziness_associated',
      category: 'dizziness',
      text: 'Do you also have chest pain or shortness of breath?',
      subtext: 'Assess for cardiovascular compromise.',
      whyText: 'Dizziness with chest pain or breathing issues could indicate a heart rhythm problem or heart attack.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, chest pain or shortness of breath', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  cuts: [
    {
      id: 'cuts_bleeding',
      category: 'cuts',
      text: 'Is the bleeding severe or spurting, and does it stop with pressure?',
      subtext: 'Arterial bleeding is a medical emergency.',
      whyText: 'Spurting blood or bleeding that will not stop after 10-15 minutes of direct pressure indicates a major vessel injury.',
      isCriticalForOutcome: true,
      options: [
        { id: 'spurting', label: 'Bleeding is severe, spurting, or will not stop with pressure', value: 'spurting', redFlag: true },
        { id: 'controlled', label: 'Bleeding is controlled with pressure', value: 'controlled' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'cuts_depth',
      category: 'cuts',
      text: 'How deep is the cut, and is there an embedded object?',
      subtext: 'Deep cuts or embedded objects require surgical care.',
      whyText: 'Embedded objects should never be removed outside a hospital, and deep cuts showing fat or muscle need sutures.',
      isCriticalForOutcome: true,
      options: [
        { id: 'embedded', label: 'There is a large embedded object', value: 'embedded', redFlag: true },
        { id: 'deep', label: 'Deep (shows fat/muscle) or gaping open', value: 'deep' },
        { id: 'superficial', label: 'Superficial (surface level scrape or small cut)', value: 'superficial' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'cuts_signs_of_infection',
      category: 'cuts',
      text: 'Are there signs of infection (red streak, pus, fever)?',
      subtext: 'Check for spreading infection or sepsis.',
      whyText: 'Red streaks spreading from the wound or a fever indicates a systemic infection that needs antibiotics.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, red streaks, pus, or fever', value: 'yes' },
        { id: 'no', label: 'No signs of infection', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  allergic_reaction: [
    {
      id: 'allergy_breathing',
      category: 'allergic_reaction',
      text: 'Are you experiencing swelling of the face/lips/tongue or difficulty breathing?',
      subtext: 'Airway compromise is the hallmark of anaphylaxis.',
      whyText: 'Throat swelling or wheezing indicates anaphylaxis, a life-threatening allergic reaction requiring epinephrine.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, swelling or breathing difficulty', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'allergy_rash',
      category: 'allergic_reaction',
      text: 'Is there a rash or hives, and how fast is it spreading?',
      subtext: 'Rapid spread suggests a severe systemic reaction.',
      whyText: 'Hives that spread rapidly over the body indicate a strong systemic allergic response.',
      isCriticalForOutcome: true,
      options: [
        { id: 'rapid', label: 'Rapidly spreading hives/rash', value: 'rapid' },
        { id: 'localized', label: 'Mild, localized rash or itch', value: 'localized' },
        { id: 'none', label: 'No rash', value: 'none' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'allergy_history',
      category: 'allergic_reaction',
      text: 'Do you have a history of severe allergic reactions (anaphylaxis) or carry an EpiPen?',
      subtext: 'Past history increases risk of current severe reaction.',
      whyText: 'Patients with known severe allergies are at high risk for rapid deterioration.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, known severe allergies', value: 'yes' },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],

  fatigue: [
    {
      id: 'fatigue_duration',
      category: 'fatigue',
      text: 'How long have you been experiencing severe fatigue?',
      subtext: 'Differentiates acute vs chronic fatigue.',
      whyText: 'Fatigue lasting more than a few weeks may indicate underlying chronic conditions, whereas acute fatigue often relates to infection.',
      isCriticalForOutcome: true,
      options: [
        { id: 'days', label: 'A few days to a week', value: 'days' },
        { id: 'weeks', label: 'Several weeks', value: 'weeks' },
        { id: 'months', label: 'More than 6 months', value: 'months' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'fatigue_associated',
      category: 'fatigue',
      text: 'Do you have any of these associated symptoms?',
      subtext: 'Check for signs of anemia, depression, or severe infection.',
      whyText: 'Fatigue accompanied by chest pain, shortness of breath, or pale skin can indicate anemia or cardiovascular issues.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'chest_pain_sob', label: 'Chest pain or shortness of breath', value: 'chest_pain_sob', redFlag: true },
        { id: 'fever_night_sweats', label: 'Fever or heavy night sweats', value: 'fever_night_sweats' },
        { id: 'depression', label: 'Persistent sad mood or lack of interest', value: 'depression' },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
    {
      id: 'fatigue_impact',
      category: 'fatigue',
      text: 'How much does the fatigue affect your daily activities?',
      subtext: 'Severity of functional impairment.',
      whyText: 'Inability to get out of bed or perform basic daily tasks warrants closer clinical evaluation.',
      isCriticalForOutcome: true,
      options: [
        { id: 'severe', label: 'Cannot perform basic daily tasks (e.g., getting out of bed)', value: 'severe' },
        { id: 'moderate', label: 'Struggling, but managing essential tasks', value: 'moderate' },
        { id: 'mild', label: 'Noticeable but fully functional', value: 'mild' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  unexplained_weight_loss: [
    {
      id: 'weight_loss_amount',
      category: 'unexplained_weight_loss',
      text: 'Approximately how much weight have you lost without trying?',
      subtext: 'Quantifying the loss helps determine urgency.',
      whyText: 'Losing more than 5% of your body weight in a short period without diet or exercise changes is a red flag for underlying disease.',
      isCriticalForOutcome: true,
      options: [
        { id: 'small', label: 'Less than 5 lbs (approx. 2 kg)', value: 'small' },
        { id: 'moderate', label: '5-10 lbs (approx. 2-4.5 kg)', value: 'moderate' },
        { id: 'significant', label: 'More than 10 lbs (approx. >4.5 kg)', value: 'significant', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'weight_loss_duration',
      category: 'unexplained_weight_loss',
      text: 'Over what period of time did this weight loss occur?',
      subtext: 'Rapid loss is more concerning.',
      whyText: 'Significant weight loss over a very short period (weeks to months) is a classic warning sign for hyperthyroidism, diabetes, or malignancy.',
      isCriticalForOutcome: true,
      options: [
        { id: 'rapid', label: 'Within a few weeks to a month', value: 'rapid' },
        { id: 'gradual', label: 'Gradually over 6 months to a year', value: 'gradual' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'weight_loss_associated',
      category: 'unexplained_weight_loss',
      text: 'Do you have any of these associated symptoms?',
      subtext: 'Select all that apply.',
      whyText: 'Weight loss with severe pain, night sweats, or changes in bowel habits increases the suspicion of serious pathology.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'night_sweats', label: 'Drenching night sweats or chronic fever', value: 'night_sweats', redFlag: true },
        { id: 'excess_thirst', label: 'Excessive thirst and frequent urination', value: 'excess_thirst' },
        { id: 'bowel_changes', label: 'Blood in stool or persistent diarrhea', value: 'bowel_changes', redFlag: true },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
  ],

  nausea_vomiting: [
    {
      id: 'nv_duration',
      category: 'nausea_vomiting',
      text: 'How long have you been vomiting or feeling severely nauseous?',
      subtext: 'Helps determine risk of dehydration.',
      whyText: 'Prolonged vomiting (over 24-48 hours) significantly increases the risk of severe dehydration and electrolyte imbalance.',
      isCriticalForOutcome: true,
      options: [
        { id: 'less_24h', label: 'Less than 24 hours', value: 'less_24h' },
        { id: '1_to_2_days', label: '1 to 2 days', value: '1_to_2_days' },
        { id: 'more_2_days', label: 'More than 2 days', value: 'more_2_days' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'nv_appearance',
      category: 'nausea_vomiting',
      text: 'Does the vomit contain blood or look like dark coffee grounds?',
      subtext: 'Coffee-ground vomit is a sign of upper GI bleeding.',
      whyText: 'Blood or coffee-ground material in vomit indicates bleeding in the stomach or esophagus, which is a medical emergency.',
      isCriticalForOutcome: true,
      options: [
        { id: 'blood', label: 'Yes, bright red blood', value: 'blood', redFlag: true },
        { id: 'coffee_grounds', label: 'Yes, looks like dark coffee grounds', value: 'coffee_grounds', redFlag: true },
        { id: 'no', label: 'No, it is clear, yellow, or food-colored', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'nv_associated',
      category: 'nausea_vomiting',
      text: 'Are you experiencing severe abdominal pain, high fever, or inability to keep any fluids down?',
      subtext: 'Check for acute abdomen or severe dehydration.',
      whyText: 'Severe pain with vomiting can indicate appendicitis or bowel obstruction. Inability to keep fluids down leads to rapid dehydration.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'severe_pain', label: 'Severe, sharp abdominal pain', value: 'severe_pain', redFlag: true },
        { id: 'no_fluids', label: 'Cannot keep any fluids down for over 12 hours', value: 'no_fluids', redFlag: true },
        { id: 'fever', label: 'High fever', value: 'fever' },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
  ],
  diarrhea: [
    {
      id: 'diarrhea_duration',
      category: 'diarrhea',
      text: 'How many days have you had diarrhea?',
      subtext: 'Acute vs chronic diarrhea.',
      whyText: 'Diarrhea lasting more than 3-5 days may require clinical investigation for bacterial infection, parasites, or inflammatory conditions.',
      isCriticalForOutcome: true,
      options: [
        { id: 'less_3_days', label: 'Less than 3 days', value: 'less_3_days' },
        { id: '3_to_5_days', label: '3 to 5 days', value: '3_to_5_days' },
        { id: 'more_5_days', label: 'More than 5 days', value: 'more_5_days' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'diarrhea_appearance',
      category: 'diarrhea',
      text: 'Is there any blood or black, tarry substance in your stool?',
      subtext: 'Checking for lower GI bleeding.',
      whyText: 'Bloody or black, tarry stools can indicate a gastrointestinal bleed or severe inflammatory bowel disease.',
      isCriticalForOutcome: true,
      options: [
        { id: 'blood', label: 'Yes, bright red blood', value: 'blood', redFlag: true },
        { id: 'black_tarry', label: 'Yes, black and tarry', value: 'black_tarry', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'diarrhea_hydration',
      category: 'diarrhea',
      text: 'Are you showing signs of severe dehydration (extreme thirst, dry mouth, little to no urination, dizziness)?',
      subtext: 'Dehydration is the primary risk of diarrhea.',
      whyText: 'Severe dehydration can lead to kidney injury and shock if not treated promptly with IV fluids.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, severe dehydration signs', value: 'yes', redFlag: true },
        { id: 'no', label: 'No, I can stay hydrated', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  constipation: [
    {
      id: 'constipation_duration',
      category: 'constipation',
      text: 'How long has it been since your last bowel movement?',
      subtext: 'Determines severity of impaction.',
      whyText: 'Going without a bowel movement for more than a week can indicate severe fecal impaction or bowel obstruction.',
      isCriticalForOutcome: true,
      options: [
        { id: 'few_days', label: 'A few days (less than a week)', value: 'few_days' },
        { id: 'one_week', label: 'About a week', value: 'one_week' },
        { id: 'more_week', label: 'More than a week', value: 'more_week' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'constipation_associated',
      category: 'constipation',
      text: 'Are you experiencing severe abdominal pain, vomiting, or a swollen/rigid abdomen?',
      subtext: 'Check for bowel obstruction.',
      whyText: 'Constipation combined with severe pain, vomiting, or a rigid abdomen strongly suggests a bowel obstruction, which is a medical emergency.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'severe_pain', label: 'Severe abdominal pain', value: 'severe_pain', redFlag: true },
        { id: 'vomiting', label: 'Repeated vomiting', value: 'vomiting', redFlag: true },
        { id: 'swollen_abdomen', label: 'Swollen or rigid abdomen', value: 'swollen_abdomen', redFlag: true },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
  ],
  blood_in_stool: [
    {
      id: 'blood_stool_color',
      category: 'blood_in_stool',
      text: 'What color is the blood in your stool?',
      subtext: 'Bright red vs black/tarry indicates bleed location.',
      whyText: 'Bright red blood usually indicates lower GI bleeding (e.g., hemorrhoids, fissures), while black, tarry stool (melena) points to upper GI bleeding (e.g., stomach ulcer) which is often more critical.',
      isCriticalForOutcome: true,
      options: [
        { id: 'bright_red', label: 'Bright red (on toilet paper or in bowl)', value: 'bright_red' },
        { id: 'dark_red', label: 'Dark red or maroon mixed in stool', value: 'dark_red' },
        { id: 'black_tarry', label: 'Black, sticky, and tarry', value: 'black_tarry', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'blood_stool_amount',
      category: 'blood_in_stool',
      text: 'How much blood is there?',
      subtext: 'Volume of blood loss.',
      whyText: 'Large amounts of blood loss can lead to hemorrhagic shock.',
      isCriticalForOutcome: true,
      options: [
        { id: 'streaks', label: 'A few streaks on the toilet paper', value: 'streaks' },
        { id: 'moderate', label: 'Noticeable amount coloring the toilet water', value: 'moderate' },
        { id: 'large', label: 'Large clots or continuous bleeding', value: 'large', redFlag: true },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'blood_stool_associated',
      category: 'blood_in_stool',
      text: 'Are you feeling dizzy, lightheaded, or having shortness of breath?',
      subtext: 'Check for signs of significant blood loss (anemia/hypovolemia).',
      whyText: 'Dizziness or fainting indicates that the blood loss is significant enough to drop blood pressure, requiring emergency care.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, feeling dizzy or lightheaded', value: 'yes', redFlag: true },
        { id: 'no', label: 'No, I feel fine otherwise', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],

  numbness_weakness: [
    {
      id: 'nw_onset',
      category: 'numbness_weakness',
      text: 'Did the numbness or weakness happen suddenly?',
      subtext: 'Sudden onset can be a sign of a stroke.',
      whyText: 'Sudden onset of neurological deficits is the hallmark of an acute vascular event like a stroke.',
      isCriticalForOutcome: true,
      options: [
        { id: 'sudden', label: 'Yes, sudden onset', value: 'sudden', redFlag: true },
        { id: 'gradual', label: 'No, gradual onset over days/weeks', value: 'gradual' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'nw_location',
      category: 'numbness_weakness',
      text: 'Where are you experiencing the numbness or weakness?',
      subtext: 'Unilateral vs bilateral.',
      whyText: 'Weakness confined to one side of the body or face is a classic stroke symptom.',
      isCriticalForOutcome: true,
      options: [
        { id: 'one_side', label: 'One side of face, arm, or leg', value: 'one_side', redFlag: true },
        { id: 'both_sides', label: 'Both sides or generalized', value: 'both_sides' },
        { id: 'specific_nerve', label: 'Small specific area (e.g., fingertips)', value: 'specific_nerve' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'nw_associated',
      category: 'numbness_weakness',
      text: 'Do you have difficulty speaking, understanding speech, or sudden vision changes?',
      subtext: 'Check for additional cortical signs.',
      whyText: 'Aphasia (speech difficulty) and visual field loss are strong indicators of a brain ischemia.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  confusion: [
    {
      id: 'confusion_onset',
      category: 'confusion',
      text: 'Did the confusion start suddenly (within hours or days)?',
      subtext: 'Delirium vs dementia.',
      whyText: 'Sudden confusion (delirium) indicates an acute medical problem such as infection, drug reaction, or stroke.',
      isCriticalForOutcome: true,
      options: [
        { id: 'sudden', label: 'Yes, sudden change', value: 'sudden', redFlag: true },
        { id: 'gradual', label: 'No, gradual change over months/years', value: 'gradual' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'confusion_associated',
      category: 'confusion',
      text: 'Are there associated symptoms like high fever, head injury, or diabetes?',
      subtext: 'Check for critical underlying causes.',
      whyText: 'Fever suggests infection (like meningitis), trauma suggests bleeding, and diabetes suggests hypoglycemia.',
      multiSelect: true,
      isCriticalForOutcome: true,
      options: [
        { id: 'fever', label: 'High fever', value: 'fever', redFlag: true },
        { id: 'head_injury', label: 'Recent head injury', value: 'head_injury', redFlag: true },
        { id: 'diabetes', label: 'History of diabetes', value: 'diabetes' },
        { id: 'none', label: 'None of the above', value: 'none' },
      ],
    },
  ],
  seizure: [
    {
      id: 'seizure_duration',
      category: 'seizure',
      text: 'How long did the seizure last, and has the person regained full consciousness?',
      subtext: 'Status epilepticus is a medical emergency.',
      whyText: 'A seizure lasting more than 5 minutes or failure to regain consciousness indicates status epilepticus, which can cause permanent brain damage.',
      isCriticalForOutcome: true,
      options: [
        { id: 'over_5_min', label: 'Lasted over 5 minutes or still ongoing', value: 'over_5_min', redFlag: true },
        { id: 'not_waking', label: 'Stopped, but person is not waking up', value: 'not_waking', redFlag: true },
        { id: 'recovered', label: 'Less than 5 minutes and fully awake now', value: 'recovered' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'seizure_history',
      category: 'seizure',
      text: 'Is this the person\'s first ever seizure?',
      subtext: 'First-time seizures require full workup.',
      whyText: 'A new-onset seizure in a patient without epilepsy requires emergent imaging and lab work to find the cause.',
      isCriticalForOutcome: true,
      options: [
        { id: 'first_time', label: 'Yes, first time ever', value: 'first_time', redFlag: true },
        { id: 'known_epilepsy', label: 'No, they have a known seizure disorder', value: 'known_epilepsy' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'seizure_injury',
      category: 'seizure',
      text: 'Did the person sustain a significant injury (e.g., hitting their head) during the seizure?',
      subtext: 'Secondary trauma assessment.',
      whyText: 'Falls during a seizure can cause severe traumatic brain injuries or fractures.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, significant injury', value: 'yes', redFlag: true },
        { id: 'no', label: 'No obvious major injury', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  fainting: [
    {
      id: 'fainting_context',
      category: 'fainting',
      text: 'What were you doing right before you fainted?',
      subtext: 'Helps distinguish cardiac vs vasovagal syncope.',
      whyText: 'Fainting during exertion without warning is highly suspicious for a dangerous heart condition (e.g., arrhythmia, structural heart disease).',
      isCriticalForOutcome: true,
      options: [
        { id: 'exertion', label: 'Exercising or physical exertion', value: 'exertion', redFlag: true },
        { id: 'standing_long', label: 'Standing for a long time', value: 'standing_long' },
        { id: 'emotion', label: 'Extreme emotion, pain, or seeing blood', value: 'emotion' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'fainting_associated',
      category: 'fainting',
      text: 'Did you experience chest pain, palpitations, or shortness of breath before fainting?',
      subtext: 'Check for cardiovascular signs.',
      whyText: 'These symptoms point to a primary cardiac cause for the faint, which can be fatal if untreated.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  joint_pain: [
    {
      id: 'joint_pain_signs',
      category: 'joint_pain',
      text: 'Is the joint hot, red, and swollen, or do you have a fever?',
      subtext: 'Rule out septic arthritis.',
      whyText: 'A hot, red, swollen joint accompanied by fever strongly suggests a joint infection (septic arthritis), which can rapidly destroy the joint.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, hot/red/swollen or fever', value: 'yes', redFlag: true },
        { id: 'no', label: 'No, just painful or stiff', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'joint_pain_injury',
      category: 'joint_pain',
      text: 'Did the pain start immediately after a significant injury or fall?',
      subtext: 'Rule out fracture.',
      whyText: 'Trauma followed by inability to bear weight or severe deformity indicates a likely fracture or severe dislocation.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes_deformity', label: 'Yes, and the joint looks deformed or I cannot bear weight', value: 'yes_deformity', redFlag: true },
        { id: 'yes_minor', label: 'Yes, minor injury, can still use it slightly', value: 'yes_minor' },
        { id: 'no', label: 'No injury', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  muscle_strain: [
    {
      id: 'muscle_strain_severity',
      category: 'muscle_strain',
      text: 'Can you move the affected muscle or bear weight on it?',
      subtext: 'Check for complete tear.',
      whyText: 'Complete inability to move a muscle group or bear weight may indicate a full muscle or tendon tear requiring surgical evaluation.',
      isCriticalForOutcome: true,
      options: [
        { id: 'cannot_move', label: 'Cannot move it at all or bear any weight', value: 'cannot_move', redFlag: true },
        { id: 'painful_move', label: 'Can move it but it is very painful', value: 'painful_move' },
        { id: 'stiff', label: 'A bit stiff and sore', value: 'stiff' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'muscle_strain_swelling',
      category: 'muscle_strain',
      text: 'Is there massive swelling, a visible dent in the muscle, or sudden severe bruising?',
      subtext: 'Signs of significant trauma.',
      whyText: 'A visible dent (palpable defect) indicates a ruptured tendon or muscle belly.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  insect_bite: [
    {
      id: 'insect_bite_anaphylaxis',
      category: 'insect_bite',
      text: 'Are you experiencing difficulty breathing, swelling of the face/tongue, or widespread hives?',
      subtext: 'Check for systemic allergic reaction.',
      whyText: 'These are signs of anaphylaxis, a life-threatening systemic allergic reaction often triggered by bee/wasp stings.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'insect_bite_infection',
      category: 'insect_bite',
      text: 'Is the bite area expanding rapidly with redness, severe pain, or red streaks?',
      subtext: 'Check for cellulitis.',
      whyText: 'Rapidly spreading redness or red streaks indicate a secondary bacterial infection (cellulitis/lymphangitis).',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes' },
        { id: 'no', label: 'No, just localized itching/swelling', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  eye_problem: [
    {
      id: 'eye_vision',
      category: 'eye_problem',
      text: 'Are you experiencing sudden vision loss, double vision, or seeing flashing lights/curtains?',
      subtext: 'Check for retinal detachment or vascular occlusion.',
      whyText: 'Sudden vision loss or visual field defects can indicate retinal detachment or a central retinal artery occlusion, both requiring immediate intervention.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'eye_pain',
      category: 'eye_problem',
      text: 'Is there severe pain in the eye, or did a chemical/object get into it?',
      subtext: 'Check for trauma or acute glaucoma.',
      whyText: 'Severe eye pain, especially with a fixed dilated pupil or chemical exposure, is a vision-threatening emergency.',
      isCriticalForOutcome: true,
      options: [
        { id: 'chemical_trauma', label: 'Yes, chemical exposure or trauma', value: 'chemical_trauma', redFlag: true },
        { id: 'severe_pain', label: 'Yes, severe aching pain', value: 'severe_pain', redFlag: true },
        { id: 'mild', label: 'Mild irritation, redness, or itching', value: 'mild' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  ear_pain: [
    {
      id: 'ear_pain_associated',
      category: 'ear_pain',
      text: 'Do you have swelling behind the ear, severe dizziness, or high fever?',
      subtext: 'Rule out mastoiditis.',
      whyText: 'Swelling behind the ear with fever indicates mastoiditis, a severe bone infection that can spread to the brain.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'ear_pain_discharge',
      category: 'ear_pain',
      text: 'Is there any discharge coming from the ear?',
      subtext: 'Check for ruptured eardrum.',
      whyText: 'Pus or bloody discharge can indicate a ruptured tympanic membrane or severe otitis externa.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, pus or blood', value: 'yes' },
        { id: 'no', label: 'No discharge', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  urinary_symptoms: [
    {
      id: 'urinary_fever_back_pain',
      category: 'urinary_symptoms',
      text: 'Do you have a high fever, chills, or severe pain in your mid-back/flank?',
      subtext: 'Rule out pyelonephritis (kidney infection).',
      whyText: 'These symptoms suggest an upper urinary tract infection (kidney infection) rather than a simple bladder infection, requiring prompt antibiotics.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, fever/chills or back pain', value: 'yes', redFlag: true },
        { id: 'no', label: 'No, just pain with urination or frequency', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'urinary_retention',
      category: 'urinary_symptoms',
      text: 'Are you completely unable to pass urine despite feeling a strong urge?',
      subtext: 'Check for acute urinary retention.',
      whyText: 'Complete inability to urinate is a medical emergency requiring catheterization to prevent bladder damage or rupture.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, cannot urinate at all', value: 'yes', redFlag: true },
        { id: 'no', label: 'No, I can still urinate', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  mental_health_concern: [
    {
      id: 'mh_safety',
      category: 'mental_health_concern',
      text: 'Are you having thoughts of harming yourself or someone else?',
      subtext: 'Assess immediate safety.',
      whyText: 'Active suicidal or homicidal ideation requires immediate psychiatric emergency intervention.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'mh_reality',
      category: 'mental_health_concern',
      text: 'Are you seeing or hearing things that others do not, or feeling severely confused?',
      subtext: 'Check for psychosis or delirium.',
      whyText: 'New onset hallucinations or severe paranoia require urgent medical/psychiatric evaluation.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
  toothache_dental_pain: [
    {
      id: 'dental_pain_duration',
      category: 'toothache_dental_pain',
      text: 'How long have you been experiencing this dental pain?',
      subtext: 'Duration helps determine urgency of dental care needed.',
      whyText: 'Dental pain lasting more than a few days is unlikely to resolve without treatment. Longer duration increases the risk of abscess formation.',
      isCriticalForOutcome: true,
      options: [
        { id: 'today', label: 'Started today or yesterday', value: 'today' },
        { id: 'a_few_days', label: 'A few days (2–5 days)', value: 'a_few_days' },
        { id: 'more_than_week', label: 'More than a week', value: 'more_than_week' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'dental_swelling',
      category: 'toothache_dental_pain',
      text: 'Are you experiencing any facial swelling, swelling around the eye, or difficulty opening your mouth?',
      subtext: 'Signs of spreading infection.',
      whyText: 'Facial swelling or trismus (inability to open mouth) indicates a deep space infection that can quickly compromise the airway or spread to the brain.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, noticeable facial swelling or stiffness', value: 'yes', redFlag: true },
        { id: 'no', label: 'No, pain is limited to the tooth/gums', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'dental_breathing',
      category: 'toothache_dental_pain',
      text: 'Are you having any difficulty swallowing or breathing?',
      subtext: 'Airway compromise.',
      whyText: 'Difficulty swallowing or breathing with dental pain strongly suggests Ludwig\'s angina or similar severe infection threatening the airway. This is a critical emergency.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes, trouble swallowing or breathing', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
    {
      id: 'dental_fever',
      category: 'toothache_dental_pain',
      text: 'Do you have a high fever?',
      subtext: 'Systemic involvement.',
      whyText: 'Fever accompanying dental pain indicates the local tooth infection has spread systemically.',
      isCriticalForOutcome: true,
      options: [
        { id: 'yes', label: 'Yes', value: 'yes', redFlag: true },
        { id: 'no', label: 'No', value: 'no' },
        NOT_SURE_OPTION,
      ],
    },
  ],
}

/**
 * Retrieve questions for a specific category
 */
export function getQuestionsForCategory(category: SymptomCategory): Question[] {
  return QUESTION_LIBRARY[category] || []
}

/**
 * Retrieve a single question definition by ID
 */
export function getQuestionById(category: SymptomCategory, questionId: string): Question | undefined {
  return QUESTION_LIBRARY[category]?.find((q) => q.id === questionId)
}
